### ISSUE TITLE
Rename `Contract` to `PluginContract`

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [loomnetwork/unity3d-sdk#16]
Since we move from plugin-based contracts more towards EVM-based contracts, I think it makes sense to rename `Contract` into a more specific `PluginContract`, because otherwise it can be assumed that plugin-based contracts are some kind of "recommended default".

**Comment by ZimM-LostPolygon** [comment]
@enlight @mattkanwisher

**Comment by enlight** [comment]
Not a big fan of the idea, it'd introduce inconsistency with the loom-js and go-loom APIs.

**Comment by ZimM-LostPolygon** [comment]
The same reasoning applies to other SDKs, so it can be a global change.
For C# at least, we can keep `Contract` for a while to not break the public
API, but emit a obsolescence warning if it is used.

**Comment by enlight** [comment]
Don't like the new name, and don't want to spend any more time on this.
